  api:
    build: .
    container_name: magicpic-api
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=35.154.148.0
      - DB_PORT=5432
      - DB_NAME=magicpin
      - DB_USER=admin
      - DB_PASSWORD=admin@123
      - SECRET_KEY=neurabit@admin
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
    restart: unless-stopped
